#!/usr/bin/python3
from sys import argv
import math

def factorize(n):
    i = 2

    if n < 2:
        return
    print()
    print(n, "<- Value before")
    while n & i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(n, n / i, i))
    print(n, "<- Value After")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as my_file:
            x = my_file.readline()

            while x != "":
                n = int(x.split('\n')[0])
                factorize(n)
                x = my_file.readline()
except:
    pass
